### ISSUE TITLE
Clouds are Not responsive (They are fixed)

### ISSUE THREAD

**Issue by harsh6975** [alishaac/Personal_Website#1]
Use position relative for the container then make the position of cloud absolute.

**Comment by alishaac** [comment]
updated the code . Can you please check it now!

**Comment by harsh6975** [comment]
Ya fine. But it's always good practice to use a percentage. 
You can use maybe left:20% top:10%. It will adjust according to the screen.
Also, use some media queries to make it more responsive although it's nice.

**Comment by alishaac** [comment]
Yeah sure.
This was made when i just had started web-dev. I'll modify it later
Thank you for the suggestions

**Comment by harsh6975** [comment]
That's Great.
Happing learning.
